version: "3.8"

networks:
  rs0-network:
    driver: bridge

services:
  rs0-1:
    image: mongo:5
    container_name: rs0-1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    volumes:
      - /Users/nautilus/data/rs0-1/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"rs0-1:27017\"},{_id:1,host:\"rs0-2:28017\"},{_id:2,host:\"rs0-3:29017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  rs0-2:
    image: mongo:5
    container_name: rs0-2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "28017"]
    volumes:
      - /Users/nautilus/data/rs0-2:/data/db
    ports:
      - 28017:28017

  rs0-3:
    image: mongo:5
    container_name: rs0-3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "29017"]
    volumes:
      - /Users/nautilus/data/rs0-3:/data/db
    ports:
      - 29017:29017